"""
Django settings for tnt_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-839yjp%olo^itcxfyq81gw#r2)_an&4gab1p!^4s%4ws+syroa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'toursntrips',
    'bookings',
    'channels'
]


ASGI_APPLICATION = 'tnt_backend.asgi.application'


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tnt_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tnt_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = False          # ← Important!
USE_TZ = True

# Force American date format globally
DATE_FORMAT = 'm/d/Y'
SHORT_DATE_FORMAT = 'm/d/Y'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For collectstatic in production
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Global static dir (optional)
    # Add app static dirs if not auto-discovered
]

# Media files (if using uploads later)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'






# Logging: print errors with tracebacks to console (useful during development)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'rest_framework': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}









HOST_EMAIL = 'vibhakarakhil@gmail.com'
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"           # ✅ Gmail SMTP server
EMAIL_PORT = 587                        # TLS port
EMAIL_USE_TLS = True                    

EMAIL_HOST_USER = "vibhakarakhil@gmail.com"   # ✅ Correct Gmail account
EMAIL_HOST_PASSWORD = "xlag kfqr vawg gfjh"    # ✅ Use App Password if 2FA enabled

DEFAULT_FROM_EMAIL = "Toss & Trips <vibhakarakhil@gmail.com>"




# settings.py
# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis URL (adjust host/port if needed)
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'  # Or your timezone, e.g., 'Asia/Kolkata'

# Optional: Beat for periodic tasks (not needed for emails)
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# INSTALLED_APPS += ['django_celery_beat']  # If using beat



# ----------------------------------------------------------------------
# 3. CORS SETTINGS – explicit origins (recommended for prod)
# ----------------------------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True          # ← Turn OFF the wildcard

# CORS_ALLOWED_ORIGINS = [
#     "https://tossandtrips.web.app",    # Your live front-end
#     "http://localhost:3000",           # Local dev (React/Vue/etc.)
#     "http://127.0.0.1:3000",
# ]

# If you need cookies / auth headers:
CORS_ALLOW_CREDENTIALS = True

# ----------------------------------------------------------------------
# 4. CSRF TRUSTED ORIGINS – needed for POST/PUT/DELETE over HTTPS
# # ----------------------------------------------------------------------
# CSRF_TRUSTED_ORIGINS = [
#     "https://*.tunnelmole.net",        # All Tunnelmole sub-domains
#     "https://tossandtrips.web.app",
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
# ]



# Optional: Debug headers
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


# ----------------------------------------------------------------------
# 5. (Optional) ALLOWED_HOSTS – you already have '*' for dev
# ----------------------------------------------------------------------
ALLOWED_HOSTS = ['*']   # fine for local / tunnelmole; tighten in prod





