# Generated by Django 5.2.7 on 2025-11-04 13:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravellerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveSmallIntegerField(default=1, help_text='Number of adults (≥ 18 years)')),
                ('children', models.PositiveSmallIntegerField(default=0, help_text='Number of children (2–17 years)')),
                ('infants', models.PositiveSmallIntegerField(default=0, help_text='Number of infants (0–2 years)')),
            ],
            options={
                'verbose_name': 'Traveller breakdown',
                'verbose_name_plural': 'Traveller breakdowns',
            },
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the lead traveller', max_length=255)),
                ('phone_number', models.CharField(help_text='International format, e.g. +12025550123', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('nationality', models.CharField(help_text='Country of citizenship', max_length=100)),
                ('check_in_date', models.DateField(help_text='Arrival / check-in date')),
                ('check_out_date', models.DateField(help_text='Departure / check-out date')),
                ('hotel_rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], help_text='Preferred hotel star rating')),
                ('is_direct_flight', models.BooleanField(default=False, help_text='Check if a direct (non-stop) flight is required')),
                ('traveller_count', models.OneToOneField(help_text='Breakdown: adults, children, infants', on_delete=django.db.models.deletion.CASCADE, related_name='traveller', to='bookings.travellercount')),
            ],
            options={
                'verbose_name': 'Traveller Booking',
                'verbose_name_plural': 'Traveller Bookings',
                'ordering': ['-check_in_date'],
            },
        ),
    ]
