# Generated by Django 5.2.7 on 2025-11-04 13:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='traveller_count',
        ),
        migrations.AddField(
            model_name='travellercount',
            name='traveller',
            field=models.OneToOneField(default=1, help_text='The booking this count belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='count', to='bookings.traveller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traveller',
            name='phone_number',
            field=models.CharField(help_text='e.g. +12025550123', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
