# Generated by Django 5.2.7 on 2025-11-04 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_traveller_traveller_count_and_more'),
        ('toursntrips', '0006_tourntrips__days_tourntrips__nights'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveller',
            options={'ordering': ['-check_in_date'], 'verbose_name': 'Traveller', 'verbose_name_plural': 'Traveller'},
        ),
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateTimeField(auto_now_add=True, help_text='When this booking was created')),
                ('notes', models.TextField(blank=True, help_text='Any special requests or notes')),
                ('tour', models.ForeignKey(help_text='The tour package being booked', on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='toursntrips.tourntrips')),
                ('traveller', models.ForeignKey(help_text='The lead traveller for this booking', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='bookings.traveller')),
            ],
            options={
                'verbose_name': 'Visiting / Booking',
                'verbose_name_plural': 'Visitings / Bookings',
                'ordering': ['-booked_on'],
                'unique_together': {('traveller', 'tour')},
            },
        ),
    ]
