# Generated by Django 5.2.7 on 2025-11-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_traveller_options_visiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiting',
            name='request_country',
            field=models.CharField(default=1, help_text='Country of origin', max_length=255),
            preserve_default=False,
        ),
    ]
