# Generated by Django 5.2.7 on 2025-11-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_visiting_request_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveller',
            options={'ordering': ['-check_in_date'], 'verbose_name': 'Traveller', 'verbose_name_plural': 'Travellers'},
        ),
    ]
