# Generated by Django 5.2.7 on 2025-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursntrips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourntrips',
            name='shadow_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
