# Generated by Django 5.2.7 on 2025-11-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursntrips', '0002_alter_tourntrips_shadow_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Adventure Styles',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='tourntrips',
            name='start_city',
        ),
        migrations.AlterField(
            model_name='tourntrips',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], help_text='Preferred hotel star rating'),
        ),
        migrations.AlterField(
            model_name='tourntrips',
            name='adventure_styles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='toursntrips.adventurestyle'),
        ),
    ]
