# Generated by Django 5.2.7 on 2025-11-04 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursntrips', '0003_adventurestyle_remove_tourntrips_start_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourntrips',
            name='start_city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tourntrips',
            name='destinations',
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='toursntrips.country')),
            ],
            options={
                'verbose_name_plural': 'Destinations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tourntrips',
            name='destinations',
            field=models.ManyToManyField(related_name='tours', to='toursntrips.destination'),
        ),
    ]
