# Generated by Django 5.2.7 on 2025-11-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursntrips', '0004_tourntrips_start_city_remove_tourntrips_destinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(default=1, help_text='Type the primary city for this destination.', max_length=255),
            preserve_default=False,
        ),
    ]
