# Generated by Django 5.2.7 on 2025-11-04 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursntrips', '0005_destination_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourntrips',
            name='_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of days (0 if unknown)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Days'),
        ),
        migrations.AddField(
            model_name='tourntrips',
            name='_nights',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of nights (0 if unknown)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nights'),
        ),
    ]
