# Generated by Django 5.2.7 on 2025-11-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursntrips', '0006_tourntrips__days_tourntrips__nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourntrips',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for the tour (optional)', null=True, upload_to='tours/', verbose_name='Tour Image'),
        ),
    ]
