# Generated by Django 5.2.7 on 2025-11-11 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursntrips', '0007_tourntrips_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourntrips',
            name='rating',
            field=models.DecimalField(decimal_places=1, help_text='Preferred hotel star rating (e.g., 4.9)', max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
